[mypy]
python_version = 3.13
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
disallow_untyped_decorators = False
strict_optional = True
follow_imports = silent
ignore_missing_imports = True
show_error_codes = True
warn_redundant_casts = True
warn_unused_ignores = False
warn_unreachable = False

[mypy-data.*]
disallow_untyped_defs = True

[mypy-routes.*]
disallow_untyped_defs = True

[mypy-app_init]
disallow_untyped_defs = True

[mypy-tests.*]
ignore_errors = True
